*** Sets of channels

fmod CHANSET is
  protecting CINNI .

  sort Chanset .
  subsort Chan < Chanset .
  op empty : -> Chanset .
  op __ : Chanset Chanset -> Chanset [assoc comm id: empty] .
  op __ : Subst Chanset -> Chanset .

  *** Eliminate duplicate elements
  vars a b : Chan .
  var CS : Chanset .
  eq a a CS = a CS .

  *** Substitution
  var S : Subst .
  eq S empty = empty .
  eq S (a CS) = (S a) (S CS) .
endfm
