*** Reduction semantics

mod SEMANTICS is
  protecting SYNTAX .

  vars P1 P1' P2 : Trm .
  var M1 M2 : SumTrm .
  var x : Qid .
  vars a b : Chan .

  *** Transitions rules without alpha equivalence
  rl [R-COM] : a < b > . P1 + M1 | a(x) . P2 + M2 => P1 | [x := b] P2 .
  rl [R-REP] : a < b > . P1 + M1 | ! a(x) . P2 + M2 => P1 | [x := b] P2 | ! a(x) . P2 .
  crl [R-PAR] : P1 | P2 => P1' | P2 if P1 => P1' /\ P1 =/= P1' .
  crl [R-RES] : [x] P1 => [x] P1' if P1 => P1' /\ P1 =/= P1' .
endm
