load CINNI .
load CHANSET .
load SYNTAX .
load SEMANTICS .

*** SC-SUM-ASSOC
red 'x{0}('x) . nil + ('y{0}('y) . nil + 'z{0}('z) . nil) == ('x{0}('x) . nil + 'y{0}('y) . nil) + 'z{0}('z) . nil .

*** SC-SUM-COMM
red 'x{0}('x) . nil + 'y{0}('y) . nil == 'y{0}('y) . nil + 'x{0}('x) . nil .

*** SC-SUM-INACT
red 'x{0}('x) . nil + nil == 'x{0}('x) . nil .

*** SC-COMP-ASSOC
red 'x{0}('x) . nil | ('y{0}('y) . nil | 'z{0}('z) . nil) == ('x{0}('x) . nil | 'y{0}('y) . nil) | 'z{0}('z) . nil .

*** SC-COMP-COMM
red 'x{0}('x) . nil | 'y{0}('y) . nil == 'y{0}('y) . nil | 'x{0}('x) . nil .

*** SC-COMP-INACT
red 'x{0}('x) . nil | nil == 'x{0}('x) . nil .

*** SC-RES
red ['x]['y] 'x{0}('x) . nil == ['y]['x] 'x{0}('x) . nil .

*** SC-RES-INACT
red ['x] nil == nil .

*** SC-RES-COMP
red 'y{0}('y) . nil | ['x] 'x{0}('x) . nil == ['x] ('y{0}('y) . nil | 'x{0}('x) . nil) .

*** NIL
search [empty] nil =>! X:EnvTrm .

quit
