load cinni .
load chanset .
load syntax .
load semantics .

*** SC-SUM-ASSOC
red 'x{0}('x) . nil + ('y{0}('y) . nil + 'z{0}('z) . nil) == ('x{0}('x) . nil + 'y{0}('y) . nil) + 'z{0}('z) . nil .

*** SC-SUM-COMM
red 'x{0}('x) . nil + 'y{0}('y) . nil == 'y{0}('y) . nil + 'x{0}('x) . nil .

*** SC-SUM-INACT
red 'x{0}('x) . nil + nil == 'x{0}('x) . nil .

*** SC-COMP-ASSOC
red 'x{0}('x) . nil | ('y{0}('y) . nil | 'z{0}('z) . nil) == ('x{0}('x) . nil | 'y{0}('y) . nil) | 'z{0}('z) . nil .

*** SC-COMP-COMM
red 'x{0}('x) . nil | 'y{0}('y) . nil == 'y{0}('y) . nil | 'x{0}('x) . nil .

*** SC-COMP-INACT
red 'x{0}('x) . nil | nil == 'x{0}('x) . nil .

*** SC-RES
red ['x]['y] 'x{0}('x) . nil == ['y]['x] 'x{0}('x) . nil .

*** SC-RES-INACT
red ['x] nil == nil .

*** SC-RES-COMP
red 'y{0}('y) . nil | ['x] 'x{0}('x) . nil == ['x] ('y{0}('y) . nil | 'x{0}('x) . nil) .

*** NIL
search {empty} nil =>! X:EnvTrm .

*** COM
search {'y{0}} 'x{0} < 'y{0} > . nil | 'x{0}('z) . nil | 'w{0}('w) . nil  =>! X:EnvTrm .

*** REP
search {'y{0}} 'x{0} < 'y{0} > . nil | ! 'x{0}('z) . nil | 'w{0}('w) . nil  =>! X:EnvTrm .

*** PAR
search {'y{0}} 'x{0} < 'y{0} > . nil | 'x{0}('z) . nil | 'w{0}('w) . nil =>! X:EnvTrm .

*** RES
search {'y{0}} ['x] ('x{0} < 'y{0} > . nil | 'x{0}('z) . nil | 'w{0}('w) . nil) =>! X:EnvTrm .

quit
